defmodule AiPair.Test.DurableFixtureStore do
  @moduledoc """
  A stand-in for `AiPair.PaneIntentStore` that answers its three API calls from a
  script, including by not answering at all.

  It exists for the four wire shapes no real store can be driven into from a test
  without either waiting on a real deadline it does not expose or destroying the
  owner: an unanswered `put`/`delete` (`durable_store_timeout`), a `list` that
  FAILED rather than found nothing (`durable_lookup_failed`), and a commit that
  completes while the coordinator is lost underneath it.

  A scripted answer is either a term to reply, `:silent` (never reply, so the
  caller meets its own call deadline), or `{:run, fun, reply}`, which runs `fun`
  in the store process BEFORE replying — that is how a commit is made to complete
  at the exact moment the fence is destroyed.
  """

  use GenServer

  @spec start_link(keyword()) :: GenServer.on_start()
  def start_link(script) when is_list(script), do: GenServer.start_link(__MODULE__, script)

  @impl true
  def init(script), do: {:ok, Map.new(script)}

  @impl true
  def handle_call(:list, _from, state), do: answer(:list, state)
  def handle_call({:put, _record}, _from, state), do: answer(:put, state)
  def handle_call({:delete, _pane_id}, _from, state), do: answer(:delete, state)

  defp answer(op, state) do
    case Map.fetch(state, op) do
      {:ok, :silent} -> {:noreply, state}
      {:ok, {:run, fun, reply}} -> run_then_reply(fun, reply, state)
      {:ok, reply} -> {:reply, reply, state}
      :error -> {:reply, {:error, unscripted(op)}, state}
    end
  end

  defp run_then_reply(fun, reply, state) do
    fun.()
    {:reply, reply, state}
  end

  defp unscripted(op) do
    %{stage: :ownership, reason: {:unscripted, op}, outcome: :unchanged, cleanup_errors: []}
  end
end

defmodule AiPair.IPC.DurableContractFixtureTest do
  @moduledoc """
  Produces every reply fixture under `test/fixtures/contracts/ipc/durable` from
  the REAL daemon, over a real unix socket, and compares the bytes.

  Contract: `docs/contracts/durable-attach-detach.org`. Until this slice the
  fixture suite (`test/ai_pair/contracts/durable_ipc_contract_test.exs`) could
  only read the frozen bytes back and check their closed shapes, because no
  producer existed. Every reply fixture is now generated by
  `AiPair.IPC.Server` answering a frame on its socket.

  ## What "compared byte for byte" means here, exactly

  A fixture carries placeholders (`<pane_id>`, `<agent>`, `<classifier>`,
  `<state>`, `<detail>`) where the value is run-dependent. So each row:

    1. decodes the frame the server actually sent;
    2. substitutes each dynamic member, asserting its exact pre-substitution
       value first, so a placeholder can never hide a wrong one;
    3. asserts the re-encoded substituted frame plus one newline equals the
       fixture file's bytes, AND that the fixture decodes to exactly the
       substituted object — the second check is order-independent, so neither
       can pass alone on an accident of member order.

  MEASURED, and stated because it is easy to assume otherwise: the frozen
  fixture bytes are in member-sorted order, which is what the repository's
  encoder emits for a STRING-keyed map. The server builds its replies as
  ATOM-keyed maps, and on this OTP a small map's atom keys iterate in atom-table
  order rather than by name, so the daemon's own frame carries the same members
  in a different order. That is exactly what the contract's "Not promised"
  section allows ("Member order or whitespace in any reply: readers parse JSON
  ... only the decoded object is contractual"), and the row
  "the frozen bytes are the member-sorted encoding of the daemon's own frame"
  below measures the relationship rather than leaving it implied.

  ## Boundary

  No live tmux server. The census and the marker are driven through
  `AiPair.Test.ScriptedTmux`, an owned adapter over a Bash stub that never execs
  tmux, and `AiPair.Test.RouteGuard` holds the `AiPair.Tmux` name for the whole
  module so a pane child's default capture is refused at the boundary instead of
  reaching the operator's server.
  """

  use ExUnit.Case, async: false

  @moduletag :capture_log

  alias AiPair.PaneIntentStore
  alias AiPair.PaneRestore.Coordinator
  alias AiPair.PaneSupervisor
  alias AiPair.Test.DurableFixtureStore
  alias AiPair.Test.PaneIntentFaultFs, as: FaultFs
  alias AiPair.Test.ReceiptBackedIPCServer
  alias AiPair.Test.RouteGuard
  alias AiPair.Test.ScriptedTmux

  @fixture_dir Path.expand("../../fixtures/contracts/ipc/durable", __DIR__)

  @pane "%9001"
  @agent "claude_code"
  @classifier "fingerprint:claude_code"
  @session "$7"
  @session_name "s9fixture"
  @pane_pid 4242
  @command "bash"
  @boot_generation "990099"
  @marker_generation "12345"
  @recv_timeout_ms 20_000

  # Every reply fixture this module claims to produce. The claim is checked
  # against the directory AND against what the rows actually asserted, so a name
  # listed here but never produced fails the module rather than passing quietly.
  @produced ~w(
    attach.error.coordinator_unavailable.json
    attach.error.durable_metadata_missing.json
    attach.error.durable_observation_ambiguous.json
    attach.error.durable_observation_changed.json
    attach.error.durable_observation_unavailable.json
    attach.error.durable_pane_unobserved.json
    attach.error.durable_store_timeout.json
    attach.error.durable_unavailable.json
    attach.error.durable_write_failed.uncertain.json
    attach.error.durable_write_failed.unchanged.json
    attach.error.fence_update_failed.json
    attach.error.marker_absent.json
    attach.error.marker_changed.json
    attach.error.marker_foreign.json
    attach.error.marker_malformed.json
    attach.error.marker_unavailable.json
    attach.error.pane_busy.json
    attach.error.session_mismatch.json
    attach.error.unresolved_operation.json
    attach.ok.committed.already_started.json
    attach.ok.committed.json
    detach.error.coordinator_unavailable.committed.json
    detach.error.coordinator_unavailable.json
    detach.error.durable_lookup_failed.json
    detach.error.durable_store_timeout.json
    detach.error.durable_unavailable.json
    detach.error.durable_withdrawal_failed.json
    detach.error.pane_busy.json
    detach.error.pane_not_found.skipped.json
    detach.ok.intent_withdrawn.json
    legacy.attach.ok.json
    legacy.detach.ok.json
  )

  setup_all do
    :persistent_term.put({__MODULE__, :produced}, MapSet.new())

    on_exit(fn ->
      produced = :persistent_term.get({__MODULE__, :produced})
      :persistent_term.erase({__MODULE__, :produced})
      missing = MapSet.difference(MapSet.new(@produced), produced)

      if MapSet.size(missing) > 0 do
        raise "claimed but never produced: #{inspect(Enum.sort(missing))}"
      end
    end)

    :ok
  end

  setup do
    root = Path.join(canonical_tmp(), "ai_pair_s9_#{System.unique_integer([:positive])}")
    File.mkdir_p!(Path.join(root, "sock"))
    File.chmod!(Path.join(root, "sock"), 0o700)
    File.chmod!(root, 0o700)
    on_exit(fn -> File.rm_rf!(root) end)

    previous =
      Map.new([:durable_attachments, :project_binding, :tmux_server], fn key ->
        {key, Application.fetch_env(:ai_pair, key)}
      end)

    on_exit(fn ->
      Enum.each(previous, fn
        {key, {:ok, value}} -> Application.put_env(:ai_pair, key, value)
        {key, :error} -> Application.delete_env(:ai_pair, key)
      end)
    end)

    guard = RouteGuard.install!()
    RouteGuard.own_pane(guard, @pane)
    _ = PaneSupervisor.stop_pane(@pane)

    {:ok, root: root, guard: guard, sock: Path.join(root, "sock/ai-pair.sock")}
  end

  # ==========================================================================
  # Legacy mode: the two fixtures that exist so the byte-identity claim is
  # checkable rather than asserted.
  # ==========================================================================

  describe "legacy mode" do
    test "an attach reply carries no durability member at all", c do
      legacy_server!(c)

      frame = request(c, %{"cmd" => "attach_pane", "pane_id" => @pane, "agent" => @agent})
      assert_fixture("legacy.attach.ok.json", frame)
    end

    test "a detach reply is today's detached status", c do
      legacy_server!(c)

      assert %{"ok" => true} =
               Jason.decode!(
                 request(c, %{"cmd" => "attach_pane", "pane_id" => @pane, "agent" => @agent})
               )

      frame = request(c, %{"cmd" => "detach_pane", "pane_id" => @pane})
      assert_fixture("legacy.detach.ok.json", frame)
    end
  end

  # ==========================================================================
  # Fence refusals. The body never ran; the reply is exactly ok, pane_id, error.
  # ==========================================================================

  describe "fence refusals" do
    test "no coordinator is registered at all", c do
      durable_server!(c)

      assert_fixture(
        "attach.error.coordinator_unavailable.json",
        request(c, durable_attach())
      )

      assert_fixture(
        "detach.error.coordinator_unavailable.json",
        request(c, %{"cmd" => "detach_pane", "pane_id" => @pane})
      )
    end

    test "another transaction holds this pane's fence", c do
      durable_server!(c)
      coordinator!()
      release = hold_fence!(@pane)

      assert_fixture("attach.error.pane_busy.json", request(c, durable_attach()))

      assert_fixture(
        "detach.error.pane_busy.json",
        request(c, %{"cmd" => "detach_pane", "pane_id" => @pane})
      )

      send(release, :release)
    end

    test "the pane is fenced unresolved by an earlier body that did not settle", c do
      durable_server!(c)
      coordinator!()

      assert {:unresolved, :fixture} =
               Coordinator.transaction(@pane, fn -> {:unresolved, :fixture} end)

      assert_fixture("attach.error.unresolved_operation.json", request(c, durable_attach()))
    end
  end

  # ==========================================================================
  # Pre-effect refusals of a durable attach: nothing started, nothing written.
  # ==========================================================================

  describe "the metadata gate and the store lookup" do
    test "every missing field is named, in the fixed order", c do
      durable_server!(c)
      coordinator!()
      Application.delete_env(:ai_pair, :project_binding)

      frame = request(c, %{"cmd" => "attach_pane", "pane_id" => @pane, "durable" => true})
      assert_fixture("attach.error.durable_metadata_missing.json", frame)
    end

    test "no store owner is registered under the binding's root", c do
      durable_server!(c)
      coordinator!()
      bind!(c.root)

      assert_fixture("attach.error.durable_unavailable.json", request(c, durable_attach()))
      refute_pane_started()
    end
  end

  describe "the census" do
    test "the census answered and holds no row for this pane", c do
      refusal_context!(c, [census([row(pane_id: "%42")])])

      assert_fixture("attach.error.durable_pane_unobserved.json", request(c, durable_attach()))
      refute_pane_started()
    end

    test "the census answered with more than one row for this pane id", c do
      refusal_context!(c, [census([row(), row(pane_pid: 4243)])])

      assert_fixture(
        "attach.error.durable_observation_ambiguous.json",
        request(c, durable_attach())
      )

      refute_pane_started()
    end

    test "the census could not be taken", c do
      refusal_context!(c, [{"no server running\n", 1, :stderr}])

      assert_fixture(
        "attach.error.durable_observation_unavailable.json",
        request(c, durable_attach())
      )

      refute_pane_started()
    end

    test "the fenced re-read of the census differed from the first", c do
      refusal_context!(c, [
        census([row()]),
        marker(c.root),
        marker(c.root),
        census([row(pane_pid: 4243)])
      ])

      assert_fixture(
        "attach.error.durable_observation_changed.json",
        request(c, durable_attach())
      )

      refute_pane_started()
    end
  end

  describe "the marker" do
    test "the conditional write reported success and the read-back found nothing", c do
      refusal_context!(c, [census([row()]), absent_marker(), {"", 0}, absent_marker()])

      assert_fixture("attach.error.marker_absent.json", request(c, durable_attach()))
      refute_pane_started()
    end

    test "a usable marker owned by another root is left alone", c do
      refusal_context!(c, [census([row()]), marker(c.root, owner_root: "/somewhere/else")])

      assert_fixture("attach.error.marker_foreign.json", request(c, durable_attach()))
      refute_pane_started()
    end

    test "a value that is present and is not the documented marker object", c do
      refusal_context!(c, [census([row()]), {"not-a-marker\n", 0}])

      assert_fixture("attach.error.marker_malformed.json", request(c, durable_attach()))
      refute_pane_started()
    end

    test "the marker source failed, which is not an absent marker", c do
      refusal_context!(c, [census([row()]), {"no server running\n", 1, :stderr}])

      assert_fixture("attach.error.marker_unavailable.json", request(c, durable_attach()))
      refute_pane_started()
    end

    test "the fenced re-read of the marker differed from the first", c do
      refusal_context!(c, [
        census([row()]),
        marker(c.root),
        marker(c.root),
        census([row()]),
        marker(c.root, generation: "54321")
      ])

      assert_fixture("attach.error.marker_changed.json", request(c, durable_attach()))
      refute_pane_started()
    end

    test "the marker names a session other than the observed pane's", c do
      refusal_context!(c, [
        census([row()]),
        marker(c.root, session_id: "$99"),
        marker(c.root, session_id: "$99")
      ])

      assert_fixture("attach.error.session_mismatch.json", request(c, durable_attach()))
      refute_pane_started()
    end
  end

  # ==========================================================================
  # The committed attach, and the two failures after the pane is registered.
  # ==========================================================================

  describe "a durable attach that commits" do
    test "the child started by this call is reported beside the commit", c do
      durable_attach_context!(c, happy_script(c.root))
      store!(c.root)

      frame = request(c, durable_attach())
      assert_fixture("attach.ok.committed.json", frame)

      assert {:ok, [record]} = PaneIntentStore.list(store_pid(c.root))
      assert record["pane_id"] == @pane
      assert record["agent"] == @agent
      assert record["classifier"] == @classifier
      assert record["session_gen"] == @marker_generation, "the READ-BACK generation is recorded"
      refute record["session_gen"] == @boot_generation
      assert record["tmux_session"] == @session_name
      assert record["pane_pid"] == @pane_pid
      assert record["project_inbox"] == c.root
    end

    test "FIRST OWNER WINS when a child is already running", c do
      durable_attach_context!(c, happy_script(c.root))
      store!(c.root)

      # The first frame is legacy-shaped: in durable mode it still takes the
      # fence, and its reply is the legacy one, byte for byte.
      first = request(c, %{"cmd" => "attach_pane", "pane_id" => @pane, "agent" => @agent})
      assert Jason.decode!(first)["started"] == true

      assert Enum.sort(Map.keys(Jason.decode!(first))) ==
               ~w(agent classifier ok pane_id started state)

      second =
        request(c, %{
          "cmd" => "attach_pane",
          "pane_id" => @pane,
          "agent" => @agent,
          "durable" => true
        })

      assert_fixture("attach.ok.committed.already_started.json", second)
    end
  end

  describe "a store failure after the pane is registered" do
    test "a commit that failed before the atomic rename leaves the bytes intact", c do
      durable_attach_context!(c, happy_script(c.root))
      fs = fault_fs!(c)
      FaultFs.inject(fs, :file_sync, 1, {:error, :eio})
      store!(c.root, fs: fs)

      assert_fixture(
        "attach.error.durable_write_failed.unchanged.json",
        request(c, durable_attach())
      )

      assert {:ok, _pid} = PaneSupervisor.whereis_pane(@pane),
             "an unrecorded live pane is preferred over an orphan record"
    end

    test "a commit that failed after the rename leaves the bytes unknown", c do
      durable_attach_context!(c, happy_script(c.root))
      fs = fault_fs!(c)
      FaultFs.inject(fs, :directory_sync, &state_dir?/1, {:error, :eio})
      store!(c.root, fs: fs)

      assert_fixture(
        "attach.error.durable_write_failed.uncertain.json",
        request(c, durable_attach())
      )
    end

    test "a put that outlived its deadline names the unanswered call, not a disk stage", c do
      durable_attach_context!(c, happy_script(c.root))
      fixture_store!(c.root, put: :silent)

      assert_fixture("attach.error.durable_store_timeout.json", request(c, durable_attach()))
    end

    test "a fence release that could not be acknowledged keeps the known outcome", c do
      durable_attach_context!(c, happy_script(c.root))
      ledger = coordinator_pid()
      fixture_store!(c.root, put: {:run, fn -> stop_ledger(ledger) end, :ok})

      assert_fixture("attach.error.fence_update_failed.json", request(c, durable_attach()))
    end
  end

  # ==========================================================================
  # Durable withdrawal.
  # ==========================================================================

  describe "a durable detach" do
    test "the record is deleted and the registered child is then stopped", c do
      durable_attach_context!(c, happy_script(c.root))
      store!(c.root)

      assert %{"persisted" => true} = Jason.decode!(request(c, durable_attach()))
      assert {:ok, _pid} = PaneSupervisor.whereis_pane(@pane)

      frame = request(c, %{"cmd" => "detach_pane", "pane_id" => @pane})
      assert_fixture("detach.ok.intent_withdrawn.json", frame)

      assert {:ok, []} = PaneIntentStore.list(store_pid(c.root))
      assert PaneSupervisor.whereis_pane(@pane) == :error
    end

    test "a store that answered and holds no such record is an answer", c do
      durable_server!(c)
      coordinator!()
      bind!(c.root)
      store!(c.root)

      assert_fixture(
        "detach.error.pane_not_found.skipped.json",
        request(c, %{"cmd" => "detach_pane", "pane_id" => @pane})
      )
    end

    test "a store nobody could reach is never reported as an absence", c do
      durable_server!(c)
      coordinator!()
      bind!(c.root)

      assert_fixture(
        "detach.error.durable_unavailable.json",
        request(c, %{"cmd" => "detach_pane", "pane_id" => @pane})
      )
    end

    test "a read that failed leaves the record's existence unknown", c do
      durable_server!(c)
      coordinator!()
      bind!(c.root)

      fixture_store!(c.root,
        list: {:error, %{stage: :poisoned, reason: :x, outcome: :uncertain, cleanup_errors: []}}
      )

      assert_fixture(
        "detach.error.durable_lookup_failed.json",
        request(c, %{"cmd" => "detach_pane", "pane_id" => @pane})
      )
    end

    test "a delete that outlived its deadline names the delete call", c do
      durable_server!(c)
      coordinator!()
      bind!(c.root)
      fixture_store!(c.root, list: {:ok, [%{"pane_id" => @pane}]}, delete: :silent)

      assert_fixture(
        "detach.error.durable_store_timeout.json",
        request(c, %{"cmd" => "detach_pane", "pane_id" => @pane})
      )
    end

    test "a typed delete failure keeps the withdrawal_failed status", c do
      durable_attach_context!(c, happy_script(c.root))
      fs = fault_fs!(c)
      # The attach's own commit is file_sync #1; the withdrawal's is #2. Naming
      # the occurrence up front keeps the target deterministic rather than
      # depending on when the injection is registered.
      FaultFs.inject(fs, :file_sync, 2, {:error, :eio})
      store!(c.root, fs: fs)

      assert %{"persisted" => true} = Jason.decode!(request(c, durable_attach()))

      assert_fixture(
        "detach.error.durable_withdrawal_failed.json",
        request(c, %{"cmd" => "detach_pane", "pane_id" => @pane})
      )
    end

    test "the record WAS deleted and the fenced child stop could not be completed", c do
      durable_attach_context!(c, happy_script(c.root))
      supervisor = Process.whereis(PaneSupervisor)
      on_exit(fn -> rebind_supervisor(supervisor) end)

      # The delete completes; the fenced stop then cannot reach its target,
      # because the supervisor's registered name is gone at that instant. The
      # ledger is untouched, so the fence itself still releases cleanly and the
      # reply is the body's own known outcome beside a coordinator failure.
      fixture_store!(c.root,
        put: :ok,
        list: {:ok, [%{"pane_id" => @pane}]},
        delete: {:run, fn -> unbind_supervisor() end, :ok}
      )

      assert %{"persisted" => true} = Jason.decode!(request(c, durable_attach()))
      assert {:ok, _pid} = PaneSupervisor.whereis_pane(@pane)

      frame = request(c, %{"cmd" => "detach_pane", "pane_id" => @pane})
      rebind_supervisor(supervisor)
      assert_fixture("detach.error.coordinator_unavailable.committed.json", frame)
    end
  end

  # ==========================================================================
  # Coverage: the claim above is checked against the directory.
  # ==========================================================================

  test "the frozen bytes are the member-sorted encoding of the daemon's own frame", c do
    legacy_server!(c)
    frame = request(c, %{"cmd" => "attach_pane", "pane_id" => @pane, "agent" => @agent})

    canonical = frame |> Jason.decode!() |> Jason.encode!()

    assert Jason.decode!(frame) == Jason.decode!(canonical),
           "the two differ only in member order, which the contract does not promise"

    assert Jason.encode!(substitute(Jason.decode!(canonical))) <> "\n" ==
             @fixture_dir |> Path.join("legacy.attach.ok.json") |> File.read!()
  end

  test "this module claims exactly the reply fixtures the contract froze" do
    on_disk =
      @fixture_dir
      |> Path.join("*.json")
      |> Path.wildcard()
      |> Enum.map(&Path.basename/1)
      |> Enum.reject(&String.starts_with?(&1, "request."))
      |> Enum.sort()

    assert Enum.sort(@produced) == on_disk
    assert length(on_disk) == 32
  end

  # --- the byte comparison ---------------------------------------------------

  defp assert_fixture(name, frame) do
    decoded = Jason.decode!(frame)
    substituted = substitute(decoded)
    expected = @fixture_dir |> Path.join(name) |> File.read!()

    assert Jason.encode!(substituted) <> "\n" == expected,
           "#{name}: bytes differ\n  produced: #{Jason.encode!(substituted)}\n  fixture:  #{String.trim_trailing(expected)}"

    assert Jason.decode!(expected) == substituted, "#{name}: the decoded objects differ"

    :persistent_term.put(
      {__MODULE__, :produced},
      MapSet.put(:persistent_term.get({__MODULE__, :produced}), name)
    )

    decoded
  end

  # Each dynamic member's exact value is asserted BEFORE it is replaced, so a
  # placeholder can never stand in for a value the producer got wrong.
  defp substitute(frame) do
    Map.new(frame, fn
      {"pane_id", value} ->
        assert value == @pane
        {"pane_id", "<pane_id>"}

      {"agent", value} ->
        assert value == @agent
        {"agent", "<agent>"}

      {"classifier", value} ->
        assert value == @classifier
        {"classifier", "<classifier>"}

      {"state", value} ->
        assert value in ~w(idle busy dialog dead unknown)
        {"state", "<state>"}

      {"coordinator_error", value} ->
        assert is_binary(value) and value != ""
        {"coordinator_error", "<detail>"}

      other ->
        other
    end)
  end

  # --- the daemon ------------------------------------------------------------

  defp legacy_server!(c) do
    Application.put_env(:ai_pair, :durable_attachments, false)
    start_server!(c, [])
  end

  defp durable_server!(c) do
    Application.put_env(:ai_pair, :durable_attachments, true)
    start_server!(c, boot_generation: @boot_generation)
  end

  defp start_server!(c, extra) do
    name = :"s9_fixture_ipc_#{System.unique_integer([:positive])}"
    opts = [inbox: c.root, name: name] ++ extra
    {:ok, pid} = ReceiptBackedIPCServer.start_link(opts)
    on_exit(fn -> stop_quietly(pid) end)
    pid
  end

  defp stop_quietly(pid) do
    if Process.alive?(pid) do
      try do
        GenServer.stop(pid, :normal, 1_000)
      catch
        :exit, _reason -> :ok
      end
    end
  end

  defp request(c, payload) do
    {:ok, client} =
      :gen_tcp.connect({:local, c.sock}, 0, [:binary, {:active, false}, {:packet, 4}], 1_000)

    :ok = :gen_tcp.send(client, Jason.encode!(payload))
    {:ok, frame} = :gen_tcp.recv(client, 0, @recv_timeout_ms)
    :gen_tcp.close(client)
    frame
  end

  defp durable_attach do
    %{"cmd" => "attach_pane", "pane_id" => @pane, "agent" => @agent, "durable" => true}
  end

  # --- collaborators ---------------------------------------------------------

  # The whole durable attach context: a durable server, a ledger, a binding and
  # a scripted adapter. The store is chosen per row.
  defp durable_attach_context!(c, steps) do
    durable_server!(c)
    coordinator!()
    bind!(c.root)
    scripted_tmux!(steps)
  end

  # The same, plus a healthy real store: the store lookup precedes the census in
  # the contract's order, so a census or marker refusal is only reachable once a
  # store owner exists. Every row below asserts nothing was written to it.
  defp refusal_context!(c, steps) do
    durable_attach_context!(c, steps)
    store!(c.root)
  end

  defp coordinator!, do: start_supervised!({Coordinator, []})

  defp coordinator_pid, do: Process.whereis(Coordinator)

  # Stopping the ledger destroys the fence the running body holds. `:normal`
  # rather than a kill, so the guardian's own teardown path runs.
  defp stop_ledger(ledger) do
    ref = Process.monitor(ledger)
    Process.exit(ledger, :shutdown)

    receive do
      {:DOWN, ^ref, :process, ^ledger, _reason} -> :ok
    after
      1_000 -> :ok
    end
  end

  defp hold_fence!(pane) do
    parent = self()

    holder =
      spawn(fn ->
        Coordinator.transaction(pane, fn ->
          send(parent, :held)

          receive do
            :release -> {:ok, :released}
          after
            30_000 -> {:ok, :expired}
          end
        end)
      end)

    assert_receive :held, 5_000
    on_exit(fn -> if Process.alive?(holder), do: send(holder, :release) end)
    holder
  end

  defp bind!(root) do
    Application.put_env(:ai_pair, :project_binding, %{
      project: "s9fixture",
      project_dir: root,
      project_inbox: root
    })
  end

  defp store!(root, opts \\ []) do
    {:ok, pid} = PaneIntentStore.start_link([root: root] ++ opts)
    RouteGuard.own_process(pid)
    on_exit(fn -> stop_quietly(pid) end)
    pid
  end

  defp store_pid(root), do: :global.whereis_name({PaneIntentStore, Path.expand(root)})

  defp fixture_store!(root, script) do
    {:ok, pid} = DurableFixtureStore.start_link(script)
    RouteGuard.own_process(pid)
    :yes = :global.register_name({PaneIntentStore, Path.expand(root)}, pid)
    on_exit(fn -> stop_quietly(pid) end)
    pid
  end

  defp fault_fs!(_c) do
    fs = FaultFs.new()
    {_module, agent} = fs
    RouteGuard.own_process(agent)
    fs
  end

  defp state_dir?([path]), do: String.ends_with?(path, "/state")
  defp state_dir?(_args), do: false

  defp unbind_supervisor do
    if Process.whereis(PaneSupervisor), do: Process.unregister(PaneSupervisor)
    :ok
  end

  defp rebind_supervisor(pid) do
    if Process.whereis(PaneSupervisor) == nil and Process.alive?(pid) do
      Process.register(pid, PaneSupervisor)
    end

    :ok
  end

  defp refute_pane_started do
    assert PaneSupervisor.whereis_pane(@pane) == :error,
           "a pre-effect refusal starts nothing"
  end

  # --- the scripted adapter --------------------------------------------------

  defp scripted_tmux!(steps) do
    {name, _dir} = ScriptedTmux.start!(steps)
    Application.put_env(:ai_pair, :tmux_server, name)
    name
  end

  # A same-owner marker is already present, so `Marker.ensure/3` writes nothing:
  # census, ensure-read, read, fenced census, fenced read.
  defp happy_script(root) do
    [census([row()]), marker(root), marker(root), census([row()]), marker(root)]
  end

  defp census(rows), do: {Enum.map_join(rows, "", &(&1 <> "\n")), 0}

  defp row(overrides \\ []) do
    fields = [
      pane_id: @pane,
      session_id: @session,
      session_name: @session_name,
      window_index: 0,
      pane_index: 0,
      pane_pid: @pane_pid,
      command: @command,
      path: "/private/tmp"
    ]

    # Overridden field by field, in place: `Keyword.merge/2` moves an overridden
    # key to the END of the list, which silently reorders the census columns and
    # makes the adapter refuse the whole row as malformed.
    Enum.map_join(fields, "|", fn {key, default} ->
      to_string(Keyword.get(overrides, key, default))
    end)
  end

  # `show-options -v` prints the value and one newline; the stored value carries
  # none, and the reader trims exactly that. The owner root is the row's own
  # binding, passed explicitly so a script built before `bind!/1` cannot drift.
  defp marker(root, overrides \\ []) do
    value = %{
      "version" => 1,
      "owner_root" => Keyword.get(overrides, :owner_root, root),
      "session_id" => Keyword.get(overrides, :session_id, @session),
      "generation" => Keyword.get(overrides, :generation, @marker_generation)
    }

    {Jason.encode!(value) <> "\n", 0}
  end

  defp absent_marker, do: {"invalid option: @ai_pair_session_incarnation\n", 1, :stderr}

  defp canonical_tmp do
    System.tmp_dir!()
    |> Path.expand()
    |> Path.split()
    |> Enum.reduce("/", fn segment, acc ->
      joined = Path.join(acc, segment)

      case File.read_link(joined) do
        {:ok, "/" <> _rest = absolute} -> absolute
        {:ok, relative} -> Path.expand(Path.join(Path.dirname(joined), relative))
        {:error, _reason} -> joined
      end
    end)
  end
end
